# Generated by Django 4.1.7 on 2023-02-27 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DMEConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islands', models.IntegerField()),
                ('date', models.DateField(verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='fitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DME_Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_x', models.CharField(max_length=200)),
                ('map_y', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('dmeconfig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dme.dmeconfig')),
                ('fitness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dme.fitness')),
            ],
        ),
    ]
