# Generated by Django 4.1.7 on 2023-02-28 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dme_map',
            name='dmeconfig',
        ),
        migrations.AddField(
            model_name='dme_map',
            name='config',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='dme.dmeconfig'),
        ),
        migrations.AddField(
            model_name='dme_map',
            name='island_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dme_map',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='dme_map',
            name='fitness',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='dme.fitness'),
        ),
        migrations.AlterField(
            model_name='dme_map',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='dmeconfig',
            name='islands',
            field=models.IntegerField(default=0),
        ),
    ]
