# Generated by Django 4.1.7 on 2023-03-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dme', '0002_remove_dme_map_dmeconfig_dme_map_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dme_map',
            name='name',
        ),
        migrations.AlterField(
            model_name='dme_map',
            name='image',
            field=models.ImageField(upload_to='images/%Y-%m-%d'),
        ),
    ]
